name: "PR history in description"
description: "Add pull request commit history to description"
inputs:
  fence:
    description: Marker fences for commit history positions in pull request bodies
    required: false
    default: "=== GH HISTORY FENCE ==="
  format:
    description: git-log format
    required: false
    default: "### %H %s%n%n%b%n"
  format_fence:
    description: Marker fences for git-log format strings in pull request bodies
    required: false
    default: "=== GH HISTORY FORMAT FENCE ==="
  gh_template:
    description: Preprocess git-log format using gh Go template
    required: false
    default: "1"
  debug:
    description: Enable debugging mode
    required: false
    default: "0"
runs:
  using: "composite"
  steps:
    - run: |
        git checkout "$GITHUB_BASE_REF"
        if ! git checkout "$GITHUB_HEAD_REF"; then
          git checkout "${GITHUB_REF/refs\//}^2"
          git checkout -b "$GITHUB_HEAD_REF"
        fi
        printf 'y' | \
          GH_PH_PAGER='cat' \
          GH_PH_DEBUG='${{ inputs.debug }}' \
          GH_PH_HISTORY_FENCE='${{ inputs.fence }}' \
          GH_PH_HISTORY_FORMAT='${{ inputs.format }}' \
          GH_PH_HISTORY_FORMAT_FENCE='${{ inputs.format_fence }}' \
          GH_PH_HISTORY_FORMAT_GH_TEMPLATE='${{ inputs.gh_template }}' \
          $GITHUB_ACTION_PATH/gh-ph
      shell: bash
