#!/usr/bin/env bash

set -eo pipefail

: "${GH_PH_DEBUG:="0"}"
if [[ "$GH_PH_DEBUG" -ne 0 ]]; then
    set -x
fi

: "${GH_PH_HISTORY_FENCE:="=== GH HISTORY FENCE ==="}"
: "${GH_PH_HISTORY_FORMAT:="### %H %s%n%n%b%n"}"
: "${GH_PH_HISTORY_FORMAT_FENCE:="=== GH HISTORY FORMAT FENCE ==="}"
: "${GH_PH_HISTORY_FORMAT_GH_TEMPLATE:="1"}"
: "${GH_PH_PAGER:="bat"}"
: "${GH_PH_PULL_REQUEST_ID:=""}"

GH_TEMPLATE_CACHE=""

function is_vim() {
    local gh_ppid
    gh_ppid="$(ps -o ppid= $PPID | tr -d ' ')"
    [[ "$(ps -o comm= "$gh_ppid")" =~ ^n?vim$ ]] || [[ "$(ps -o comm= "$gh_ppid")" =~ /n?vim$ ]]
}

function gh_template() {
    local format="$1"
    if [[ -z "$GH_TEMPLATE_CACHE" ]]; then
        local fields
        fields="$(set -eo pipefail; (gh pr view --json 2>&1 || true) | tail -n+2 | tr -d ' ' | grep -v stateReason | paste -d, -s -)"
        GH_TEMPLATE_CACHE="$(set -eo pipefail; gh pr view "$GH_PH_PULL_REQUEST_ID" --json "$fields" --template "$format")"
    fi
    printf '%s' "$GH_TEMPLATE_CACHE"
}

function git_log_format() {
    if [[ -z "$GH_PH_HISTORY_FORMAT_GH_TEMPLATE" ]] || [[ "$GH_PH_HISTORY_FORMAT_GH_TEMPLATE" -eq 0 ]]; then
        printf '%s' "$GH_PH_HISTORY_FORMAT"
    else
        local gh_processed_format
        gh_processed_format="$(set -eo pipefail; gh_template "$GH_PH_HISTORY_FORMAT")"
        printf '%s' "$gh_processed_format"
    fi
}

function render_changes() {
    local target_branch="$1"
    local final_log_format
    final_log_format="$(set -eo pipefail; git_log_format)"
    git log --reverse --format="$final_log_format" "$target_branch.."
}

function inject_history() {
    local target_branch="$1"

    local line
    local rendering=0
    local updating_format=0
    while IFS='' read -r line; do
        if [[ "$rendering" -eq 1 ]] && [[ "$line" != *"$GH_PH_HISTORY_FENCE"* ]]; then
            # Placing format fences inside history fences is not allowed
            continue
        fi
        if [[ "$updating_format" -eq 1 ]] && [[ "$line" != *"$GH_PH_HISTORY_FORMAT_FENCE"* ]]; then
            # All lines are join together. Use %n for line breaks
            GH_PH_HISTORY_FORMAT+="$line"
            printf '%s\n' "$line"
            continue
        fi

        printf '%s\n' "$line"
        case "$line" in
            *"$GH_PH_HISTORY_FENCE"*)
                rendering=$(( 1 - rendering ))
                if [[ "$rendering" -eq 1 ]]; then
                    render_changes "$target_branch"
                fi
                ;;
            *"$GH_PH_HISTORY_FORMAT_FENCE"*)
                updating_format=$(( 1 - updating_format ))
                if [[ "$updating_format" -eq 1 ]]; then
                    GH_PH_HISTORY_FORMAT=''
                    GH_TEMPLATE_CACHE=''
                fi
                ;;
        esac
    done
}

function pager() {
    case "$GH_PH_PAGER" in
        bat)
            bat -l markdown
            ;;
        *)
            sh -c "$GH_PH_PAGER"
            ;;
    esac
}

function unix2dos() {
    tr -d $'\r' | sed 's/$/\r/'
}

PR_DETAILS="$(set -eo pipefail; gh pr view "$GH_PH_PULL_REQUEST_ID" --json baseRefName,body)"
PR_BASE="$(set -eo pipefail; jq -r '.baseRefName' <<<"$PR_DETAILS")"
PR_BODY="$(set -eo pipefail; jq -r '.body' <<<"$PR_DETAILS")"

inject_history "$PR_BASE" <<<"$PR_BODY" | unix2dos | pager

if read -r -n1 -p 'Update pull request body? [y/n] '; then
    printf '\n'
    if [[ "$REPLY" == 'y' ]]; then
        inject_history "$PR_BASE" <<<"$PR_BODY" | unix2dos | gh pr edit "$GH_PH_PULL_REQUEST_ID" --body-file -
    else
        printf 'Aborted\n'
    fi
elif is_vim; then
    printf '\nVim detected\n'
    inject_history "$PR_BASE" <<<"$PR_BODY" | unix2dos | gh pr edit "$GH_PH_PULL_REQUEST_ID" --body-file -
fi
