name: Pull request history

on:
  pull_request:

jobs:
  gh-ph:
    name: Add commit history to pull request description
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: Frederick888/gh-ph@master
        with:
          format: "- %H %s"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
