name: Pull request history

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  gh-ph:
    name: Add commit history to pull request description
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Frederick888/gh-ph@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
