name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conventional Commit Changelog
        id: conventional_commits
        shell: bash
        run: |
          curl -s -L -o./clog.tar.gz https://github.com/clog-tool/clog-cli/releases/download/v0.9.3/clog-v0.9.3-x86_64-unknown-linux-musl.tar.gz
          tar -xf ./clog.tar.gz
          chmod +x ./clog
          # delete current tag locally so clog uses last tag as --from
          git tag -d "$GITHUB_REF_NAME"
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          ./clog -F --setversion="$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Determine release type
        id: release_type
        shell: bash
        run: |
          is_pre='false'
          [[ "$GITHUB_REF_NAME" == *"-"* ]] && is_pre='true'
          printf '::set-output name=is_pre::%s\n' "$is_pre"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          draft: ${{ steps.release_type.outputs.is_pre }}
          prerelease: ${{ steps.release_type.outputs.is_pre }}
          body: ${{ env.CHANGELOG }}
          token: ${{ secrets.GITHUB_TOKEN }}
